### ISSUE TITLE
Server crash under some events when trying to connect to lovense toy.

### ISSUE THREAD

**Issue by Fedack** [buttplugio/buttplug-rs#116]
**Describe the bug**
Sometimes when trying to pair with a toy, an unhandled exception get thrown and the server crash. Stracktrace below. This doesn't happen all the time, usually a server restart and client reconnect fixes it.

**Expected behavior**
The toy pair normally and is added to the device list.

**Additional context**
pi@raspberrypi:~/rust/v3 $ sudo RUST_LOG=info RUST_BACKTRACE=1 ./intiface-cli --wsinsecureport 8500 --wsallinterfaces
[2020-05-09T21:51:28Z INFO  intiface_cli::options] Intiface CLI Options: Websocket Use All Interfaces option passed.
[2020-05-09T21:51:28Z INFO  intiface_cli::options] Intiface CLI Options: Websocket Insecure Port 8500
[2020-05-09T21:51:28Z INFO  intiface_cli] Intiface CLI Setup finished, running server tasks until all joined.
[2020-05-09T21:57:27Z INFO  intiface_cli::websocket] Websocket Insecure: Got connection
[2020-05-09T21:57:27Z INFO  intiface_cli::websocket] New WebSocket connection.
[2020-05-09T21:57:27Z INFO  buttplug::server::wrapper::json_wrapper] Setting JSON Wrapper message version to Version1
[2020-05-09T21:57:32Z INFO  btleplug::bluez::adapter] DevInfo: HCIDevInfo { dev_id: 0, name: [104, 99, 105, 48, 0, 0, 0, 0], bdaddr: B8:27:EB:C6:8B:9F, flags: 5, type_: 3, features: [191, 254, 207, 254, 219, 255, 123, 135], pkt_type: 52472, link_policy: 5, link_mode: 32768, acl_mtu: 1021, acl_pkts: 8, sco_mtu: 64, sco_pkts: 1, stat: HCIDevStats { err_rx: 0, err_tx: 0, cmd_tx: 296, evt_rx: 68907, acl_tx: 164, acl_rx: 164, sco_tx: 0, sco_rx: 0, byte_rx: 2503655, byte_tx: 6926 } }
[2020-05-09T21:57:32Z INFO  buttplug::server::comm_managers::btleplug] Starting scan.
[2020-05-09T21:57:32Z INFO  buttplug::device::configuration_manager] Looking for protocol that matches spec: BluetoothLE(BluetoothLESpecifier { names: {"[TV] Samsung 8 Series (55)"}, services: {} })
[2020-05-09T21:57:32Z INFO  buttplug::device::configuration_manager] No protocol found for spec!
[2020-05-09T21:57:32Z INFO  buttplug::device::configuration_manager] Looking for protocol that matches spec: BluetoothLE(BluetoothLESpecifier { names: {"HTC BS 5BA1A9"}, services: {} })
[2020-05-09T21:57:32Z INFO  buttplug::device::configuration_manager] No protocol found for spec!
[2020-05-09T21:57:32Z INFO  buttplug::device::configuration_manager] Looking for protocol that matches spec: BluetoothLE(BluetoothLESpecifier { names: {"HTC BS A43CCE"}, services: {} })
[2020-05-09T21:57:32Z INFO  buttplug::device::configuration_manager] No protocol found for spec!
[2020-05-09T21:57:42Z INFO  buttplug::device::configuration_manager] Looking for protocol that matches spec: BluetoothLE(BluetoothLESpecifier { names: {"LVS-P36"}, services: {} })
[2020-05-09T21:57:42Z INFO  buttplug::device::configuration_manager] Looking for protocol lovense
[2020-05-09T21:57:42Z INFO  buttplug::device::configuration_manager] Found a protocol definition for lovense
[2020-05-09T21:57:42Z INFO  buttplug::device::configuration_manager] Found a protocol implementation for lovense
[2020-05-09T21:57:42Z INFO  buttplug::server::comm_managers::btleplug::btleplug_internal] Connecting to device!
[2020-05-09T21:57:42Z INFO  btleplug::bluez::adapter] connected to LEConnInfo { handle: 64, role: 0, bdaddr: D7:E2:E5:EC:AF:52, bdaddr_type: 1, interval: 39, latency: 0, supervision_timeout: 42, master_clock_accuracy: 0 }
thread 'async-std/executor' panicked at 'called `Result::unwrap()` on an `Err` value: Other("ENOSYS: Function not implemented")', /cargo/registry/src/github.com-1ecc6299db9ec823/buttplug-0.2.4/src/server/comm_managers/btleplug/btleplug_internal.rs:104:5
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.44/src/backtrace/libunwind.rs:86
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.44/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:78
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1063
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1426
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:204
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:224
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:470
  11: rust_begin_unwind
             at src/libstd/panicking.rs:378
  12: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
  13: core::option::expect_none_failed
             at src/libcore/option.rs:1211
  14: <std::future::GenFuture<T> as core::future::future::Future>::poll
  15: async_task::raw::RawTask<F,R,S,T>::run
  16: std::thread::local::LocalKey<T>::with
  17: async_std::task::executor::pool::main_loop
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Aborted

**Comment by qdot** [comment]
This is a combo of an .unwrap() in buttplug (will resolve this bug when that's a handled result) and some sort of problem in btleplug which will need better error info (will file a followup over there)

**Comment by Fedack** [comment]
@qdot This is happening about every connect, I have to try two or three times to get it to work.
