### ISSUE TITLE
Server crashing when receiving a stop_scanning() and the server isn't scanning.

### ISSUE THREAD

**Issue by Fedack** [buttplugio/buttplug-rs#117]
**Describe the bug**
When sending stop_scanning() but the server isn't scanning, it just crashes. I feel it should just ignore the command.

**Expected behavior**
The server ignores the command or maybe just replies that the server isn't scanning.

**Actual behavior**
Beep boop I will now explode. (Maybe check if the same thing happen when the server receives a start_scanning() and it is already scanning?)

**Additional context**
thread 'async-std/executor' panicked at 'called `Result::unwrap()` on an `Err` value: ButtplugDeviceError(ButtplugDeviceError { message: "Scanning not currently happening." })', /cargo/registry/src/github.com-1ecc6299db9ec823/buttplug-0.3.0/src/server/wrapper/json_wrapper.rs:205:29
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.44/src/backtrace/libunwind.rs:86
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.44/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:78
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1063
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1426
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:204
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:224
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:470
  11: rust_begin_unwind
             at src/libstd/panicking.rs:378
  12: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
  13: core::option::expect_none_failed
             at src/libcore/option.rs:1211
  14: <std::future::GenFuture<T> as core::future::future::Future>::poll
  15: <std::future::GenFuture<T> as core::future::future::Future>::poll
  16: async_task::raw::RawTask<F,R,S,T>::run
  17: std::thread::local::LocalKey<T>::with
  18: async_std::task::executor::pool::main_loop
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

**Comment by qdot** [comment]
Fixed on dev, will be released in v0.5
